version: '3.8'

services:
  frontend:
    build:
      context: ./app
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./back
    ports:
      - "8000:8000"
    restart: always
