name: Deploy React and FastAPI to AWS

on:
  push:
    branches-ignore:
      - feedback

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build React app
        working-directory: app
        run: |
          npm install
          npm run build

      - name: Install backend dependencies
        working-directory: back
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_TEST }}
          username: ubuntu  
          key: ${{ secrets.KEY_TEST }}
          port: 22
          script: |
            mkdir -p ~/deploy

            rm -rf ~/deploy/app
            rm -rf ~/deploy/back
            cp -r app ~/deploy/
            cp -r back ~/deploy/

            cd ~/deploy
            docker-compose down
            docker-compose up --build -d

