name: Deploy React and FastAPI to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build React app
        working-directory: app
        run: |
          npm install
          npm run build

      - name: Install backend dependencies
        working-directory: back
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to AWS
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # Diretório do deploy
            mkdir -p ~/deploy

            # Copiar arquivos do frontend e backend
            rm -rf ~/deploy/app
            rm -rf ~/deploy/back
            scp -r app ~/deploy/
            scp -r back ~/deploy/

            # Rodar Docker Compose
            cd ~/deploy
            docker-compose down
            docker-compose up --build -d
