name: Deploy React and FastAPI to AWS

on:
  push:
    branches-ignore:
      - feedback

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to AWS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_TEST }}
          username: ubuntu
          key: ${{ secrets.KEY_TEST }}
          port: 22
          source: './app ./back ./docker-compose.yml .dvc .dvcignore'
          target: ~/deploy     

      - name: Run Deployment Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_TEST }}
          username: ubuntu
          key: ${{ secrets.KEY_TEST }}
          port: 22
          script: |
            # Instalar dependências necessárias
            sudo apt update
            sudo apt install -y python3-pip
            pip install --no-cache-dir dvc[s3]  # Ajuste o tipo de remoto do DVC aqui

            # Configurar acesso ao DVC remoto (se necessário)
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }}

            # Ir para o diretório de deploy
            cd ~/deploy

            # Baixar os arquivos de modelo com DVC
            dvc pull

            # Subir os containers Docker
            if ! [ -x "$(command -v docker-compose)" ]; then
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            docker-compose down
            docker-compose up --build -d
