name: Deploy React and FastAPI

on:
  push:
    branches:
      - main  # Altere para a branch que desejar monitorar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configuração do Node.js para build do React
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instalar dependências e build do frontend
      - name: Install and build React app
        working-directory: app
        run: |
          npm install
          npm run build

      # 4. Configuração do Python para o backend
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # 5. Instalar dependências do backend
      - name: Install backend dependencies
        working-directory: back
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 6. Fazer deploy (exemplo usando Docker)
      - name: Deploy application
        run: |
          docker-compose -f docker-compose.prod.yml up --build -d
