version: '3.8'

services:
  frontend:
    image: react-frontend:latest
    build:
      context: ./app
    ports:
      - "80:80"
    restart: always

  backend:
    image: fastapi-backend:latest
    build:
      context: ./back
    ports:
      - "8000:8000" 
    restart: always
