version: '3.8'

services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Porta do React em produção
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Porta do FastAPI
